# Generated by Django 3.0.3 on 2021-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField(unique=True)),
                ('roll_no', models.IntegerField(unique=True)),
                ('subject', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
