# Generated by Django 3.0.3 on 2021-04-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_user',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
