# Generated by Django 3.0.3 on 2021-04-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup_user_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_user',
            name='contact_no',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='roll_no',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
