# Generated by Django 3.0.3 on 2021-04-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210408_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_user',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
