# Generated by Django 3.0.3 on 2021-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210410_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_user',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
